---
  unused: OK
  currentDefault : '1'
  browsers:
    '1':
      name: "Firefox"
      icon: "./firefox.png"
      path: "$PROGRAMFILES(X86)/Mozilla Firefox/firefox.exe"
      args:
      - '1'
      - '2'
    '2':
      name: "Chrome"
      icon: "./firefox.png"
      path: "$PROGRAMFILES(X86)/Mozilla Firefox/firefox.exe"
      args:
      - '1'
      - '2'
    '3':
      name: "Opera"
      icon: "./firefox.png"
      path: "$PROGRAMFILES(X86)/Mozilla Firefox/firefox.exe"
      args:
      - '1'
      - '2'
  